title: AIWolf.NET
description: AIWolf(Artificial Intelligence based Werewolf) library for .NET Framework.
google_analytics: 
show_downloads: true
theme: jekyll-theme-hacker

gems:
  - jekyll-mentions
